### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by speartaker** [pvc988/woot64#1]
Hey man,

Your OS seemed interesting so I wanted to try it out.
The only problem is that I cannot build it. I keep getting stuff like:

/usr/bin/ld: cannot find -lwoot
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:29: recipe for target 'windowmanager' failed
make[2]: *** [windowmanager] Error 1

/usr/bin/ld: cannot find -lwoot
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:29: recipe for target 'ted' failed
make[2]: *** [ted] Error 1

and hdd.img doesn't get created at all.

I was wondering if you would be interested in solving this?

**Comment by pvc988** [comment]
Hi, @speartaker!
I would be very interested in solving this problem.
Build system is basically one big, nasty hack so It sure needs some improvement. Could you tell me what OS are you using for building? System architecture, clang, gcc, make and binutils versions would also be helpful. If possible, I would setup a VM similar to yours on my side and try to fix the problem.

**Comment by speartaker** [comment]
I use KDE Neon. clang (version 6.0.0-1ubuntu2) (for your OS at least, not for mine), 64 bit Intel CPU, more than enough RAM, make 4.1, binutils 2.30

**Comment by speartaker** [comment]
I use KDE Neon, Clang (version 6.0.0-1ubuntu2) (for your OS, not for mine), 64 bit Intel CPU, 8 GB RAM, Make 4.1, Binutils 2.30

**Comment by pvc988** [comment]
Your OS seems to be Ubuntu based. Originally I was creating everything on plain Ubuntu 18.04 so that shouldn't be a problem. clang, make and binutils seem to also match. Have you tried latest version? I've changed musl makefile a bit because it was using wrong ar and ranlib. libwoot depends on C library. And windowmanager and ted both depend on libwoot.
Just 2 days ago I've switched to Arch and my OS builds fine on it but crashes in /bin/init. So it might happen to you as well. Also make sure to NOT use multithreaded make (-jX option) since it tends to glitch sometimes.

**Comment by speartaker** [comment]
When I run make hdd.img this happens:
grub-install: error: cannot find EFI directory.

**Comment by pvc988** [comment]
Your GRUB assumes you want to install UEFI version of it which is wrong. I've just added hard disk image template file (hdd-grub-ext2.img.gz) with grub preinstalled so all that grub-install business is not needed anymore.

**Comment by speartaker** [comment]
Success!
Some suggestions:

- When running make install make sure to run it as sudo
- Change /usr/bin/qemu-system-x86_64 to qemu-system-x86_64 or else it won't work

**Comment by speartaker** [comment]
I found a bug: mouse is super super jumpy and buggy, you can't control anything with it.

**Comment by pvc988** [comment]
I wouldn't suggest to make it as superuser. You may easily overwrite something important on your build system and completely bork it. Better find where your permissions are not right and fix only that.

That QEMU thing is supposed to be like that. You are supposed to change it in the Makefile yourself to match what's on your system.

About jumpy mouse. Open another issue so I can keep separate bugs as separate issues.
