### ISSUE TITLE
QEMU Jumpy Mouse Bug

### ISSUE THREAD

**Issue by speartaker** [pvc988/woot64#2]
It just goes all over the place. You can't use it. You have to move it super super slowly or else it won't get where you want it to go and will just jump in a random direction.
![woot64mousebug](https://user-images.githubusercontent.com/30736707/61241403-b7371a80-a743-11e9-8e13-6369226c3e50.gif)

**Comment by pvc988** [comment]
I've noticed some annoying mouse behaviour in some VMs as well so I've disabled mouse acceleration. Did it fix it for you?
